-- FKlarni olib tashlash
ALTER TABLE "public"."orders" DROP CONSTRAINT "orders_room_id_fkey";
ALTER TABLE "public"."orders" DROP CONSTRAINT "orders_user_id_fkey";
ALTER TABLE "public"."photos" DROP CONSTRAINT "photos_room_id_fkey";
ALTER TABLE "public"."profile" DROP CONSTRAINT "profile_user_id_fkey";
ALTER TABLE "public"."reviews" DROP CONSTRAINT "reviews_room_id_fkey";
ALTER TABLE "public"."reviews" DROP CONSTRAINT "reviews_user_id_fkey";
ALTER TABLE "public"."rooms" DROP CONSTRAINT "rooms_category_id_fkey";
ALTER TABLE "public"."videos" DROP CONSTRAINT "videos_room_id_fkey";

-- No-unique index (phone) ni olib tashlash (kolonni ham drop qilamiz)
DROP INDEX IF EXISTS "public"."users_phone_key";

-- ORDERS
ALTER TABLE "public"."orders"
  DROP CONSTRAINT "orders_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "room_id" TYPE integer USING "room_id"::integer,
  ALTER COLUMN "duration" TYPE integer USING "duration"::integer,
  ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer,
  ALTER COLUMN "total_amount" TYPE integer USING "total_amount"::integer;
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");

-- PHOTOS
ALTER TABLE "public"."photos"
  DROP CONSTRAINT "photos_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "room_id" TYPE integer USING "room_id"::integer;
ALTER TABLE "public"."photos" ADD CONSTRAINT "photos_pkey" PRIMARY KEY ("id");

-- PROFILE
ALTER TABLE "public"."profile"
  DROP CONSTRAINT "profile_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "public"."profile" ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("id");

-- REVIEWS
ALTER TABLE "public"."reviews"
  DROP CONSTRAINT "reviews_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "room_id" TYPE integer USING "room_id"::integer,
  ALTER COLUMN "user_id" TYPE integer USING "user_id"::integer;
ALTER TABLE "public"."reviews" ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");

-- ROOM CATEGORY
ALTER TABLE "public"."room_category"
  DROP CONSTRAINT "room_category_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "public"."room_category" ADD CONSTRAINT "room_category_pkey" PRIMARY KEY ("id");

-- ROOMS
ALTER TABLE "public"."rooms"
  DROP CONSTRAINT "rooms_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "room_number"   TYPE integer USING "room_number"::integer,
  ALTER COLUMN "price_per_day" TYPE integer USING "price_per_day"::integer,
  ALTER COLUMN "beds"          TYPE integer USING "beds"::integer,
  ALTER COLUMN "bathrooms"     TYPE integer USING "bathrooms"::integer,
  ALTER COLUMN "floor"         TYPE integer USING "floor"::integer,
  ALTER COLUMN "category_id"   TYPE integer USING "category_id"::integer;
ALTER TABLE "public"."rooms" ADD CONSTRAINT "rooms_pkey" PRIMARY KEY ("id");

-- USERS
ALTER TABLE "public"."users"
  DROP CONSTRAINT "users_pkey",
  DROP COLUMN IF EXISTS "phone",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "email" SET NOT NULL;
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- VIDEOS
ALTER TABLE "public"."videos"
  DROP CONSTRAINT "videos_pkey",
  ALTER COLUMN "id" DROP DEFAULT,
  ALTER COLUMN "id" TYPE integer USING "id"::integer,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "room_id" TYPE integer USING "room_id"::integer;
ALTER TABLE "public"."videos" ADD CONSTRAINT "videos_pkey" PRIMARY KEY ("id");

-- FKlarni qayta tiklash
ALTER TABLE "public"."profile"
  ADD CONSTRAINT "profile_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_room_id_fkey"
  FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "public"."rooms"
  ADD CONSTRAINT "rooms_category_id_fkey"
  FOREIGN KEY ("category_id") REFERENCES "public"."room_category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "public"."photos"
  ADD CONSTRAINT "photos_room_id_fkey"
  FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "public"."videos"
  ADD CONSTRAINT "videos_room_id_fkey"
  FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "public"."reviews"
  ADD CONSTRAINT "reviews_room_id_fkey"
  FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "public"."reviews"
  ADD CONSTRAINT "reviews_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
